development:
  adapter: postgresql
  encoding: unicode
  <% if ENV.key?('DATABASE_HOST') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  <% end %>
  database: <%= ENV.fetch('DATABASE_NAME', 'openbill_development') %>
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_NAME_TEST') { "openbill_test_#{require 'digest'; Digest::MD5.hexdigest(`pwd`.chomp)[0,8]}" } %>
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>
  username: <%= ENV.fetch('DATABASE_USER', '') %>
  password: <%= ENV.fetch('DATABASE_PASS', '') %>

production:
  adapter: postgresql
  encoding: unicode
  <% if ENV.key?('DATABASE_HOST') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  <% end %>
  database: <%= ENV.fetch('DATABASE_NAME', 'openbill_production') %>
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
