development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'kiiiosk_production' ) %>
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: kormilica_test
  pool: 5
  username:
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: kormilica_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  reconnect: true
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'merchantly_production' ) %>
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
